# Generated by Django 5.2.17 on 2026-08-15 10:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("employee", "Employee"),
                            ("freelancer", "Freelancer"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("source_seed", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "source_seed"),
                        name="unique_account_per_profile_and_seed",
                    )
                ],
            },
        ),
    ]
